### ISSUE TITLE
Consider moving dependency mgmt from glide to dep

### ISSUE THREAD

**Issue by wkharold** [Cidan/sheep#3]
The dep tool is emerging as the standard dependency mgmt mechanism for golang projects. The glide README even recommends migrating to dep.

**Comment by Cidan** [comment]
I'll leave this as an open item -- I've used dep on and off over the last year, and it still isn't quite where it should be compared to glide on several fronts. When dep is a bit more mature, we should make that flip.

**Comment by Cidan** [comment]
fixed! moved to go modules
